# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"

stages:
  - stage: Test
    jobs:
      - job: 'validateandtest'
        pool:
          vmimage: windows-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'AzureRmPipeline-conn'
            subscriptionId: '0078d48a-8673-4c63-a3ce-6eef727d19d9'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'DevOps'
            location: 'West Europe'
            templateLocation: 'URL of the file'
            csmFileLink: 'https://raw.githubusercontent.com/Hasjiem/AzureRmPipeline-repo/main/StorageAccount/azuredeploy.json'
            csmParametersFileLink: 'https://raw.githubusercontent.com/Hasjiem/AzureRmPipeline-repo/main/StorageAccount/azuredeploy.parameters.json'
            overrideParameters: '-storageAccountPrefix "stlit"'
            deploymentMode: 'Validation'
  - stage: Deploy
    dependsOn: Test
    condition: succeeded('Test')
    jobs:
      - job: "deployARM"
        pool:
          vmimage: windows-latest
        steps: 
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'AzureRmPipeline-conn'
            subscriptionId: '0078d48a-8673-4c63-a3ce-6eef727d19d9'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'DevOps'
            location: 'West Europe'
            templateLocation: 'URL of the file'
            csmFileLink: 'https://raw.githubusercontent.com/Hasjiem/AzureRmPipeline-repo/main/StorageAccount/azuredeploy.json'
            csmParametersFileLink: 'https://raw.githubusercontent.com/Hasjiem/AzureRmPipeline-repo/main/StorageAccount/azuredeploy.parameters.json'
            overrideParameters: '-storageAccountPrefix "stlit"'
            deploymentMode: 'Incremental'
